### ISSUE TITLE
Coin integration: wishlist

### ISSUE THREAD

**Issue by phaazon** [LedgerHQ/lib-ledger-core#164]
# Community wishlist

This issue is used as a tracker for currencies that people from our community would like to be integrated in lib-ledger-core. If you want a coin integrated, please comment on this issue.

> Disclaimer: this is only a tracking list. A currency (one you want or even yours) listed here doesn’t mean it’s necessarily going to be integrated. Coin integration is currently a work in progress and implies internal strategy decisions that cannot be automated. **This is just a community wishlist, not a roadmap**.

> Disclaimer²: please be respectful towards each others’ wishes. Especially, please try to avoid heated discussion, especially about hard forks, that tend to divide people more than unite them.

If you want to contribute and if you haven’t read it already, we have a [CONTRIBUTING document](https://github.com/LedgerHQ/lib-ledger-core/blob/master/CONTRIBUTING.md) stating which type of contribution we accept. Thank you.

---

  - Energi (NRG) #141.
  - NIX (NIX) #94.
  - Unobtanium (UNO) #55.
  - lbry_credits #24.
  - Gamecredits #44

**Comment by Apuxa** [comment]
ZCOIN

**Comment by sleepdefic1t** [comment]
Hello 👋 

Just requesting the addition of ARK to the wishlish.
I'll keep an eye out for coin integration updates from LedgerHQ in the mean time 👍 

- [ARK.io](https://ark.io)
- [GitHub/ArkEcosystem/](https://github.com/ArkEcosystem/)
- [GitHub/LedgerHQ/ledger-app-ark](https://github.com/LedgerHQ/ledger-app-ark)

Please, and thank you.

**Comment by Sami32** [comment]
Hello there,

I vote for Cardano add ;)

Kind regards,

**Comment by AmazingDreams** [comment]
I have been working to add EFL support, however it is unclear to me whether that has been a waste of time or not. Your documentation implies you can submit a request and have it be reviewed which seems reasonable (https://ledger.readthedocs.io/en/latest/additional/publishing_an_app.html#deliverables-summary), however looking at PR / issue history you don't add coins as a *policy*.

Please add EFL to the wishlist and let me know if / when I can finish up the work for a merge. https://egulden.org/

**Comment by gagbo** [comment]
Hello,

(Disclaimer: this is just a fast answer from me, my views are my own and don't reflect what my employers think. Bla bla bla...)

Libledger-core project is being deprecated in favor integrating wallet features directly in https://github.com/LedgerHQ/ledger-live-common in JS (or in Scala for B2B Ledger Entreprise Services). Therefore I am closing this issue.

For Ledger Live integration, please go to [the new developer portal](https://developers.ledger.com/) for more information about integrating a new coin, which happens to have an invite link to "Ledger devs" slack where you can ask questions directly to other app implementors, coin integrators, and Ledger engineers.

Regards,
Gerry
