### ISSUE TITLE
Address verification

### ISSUE THREAD

**Issue by ibiscp** [LedgerHQ/lib-ledger-core#244]
The addresses are too big for Ledger Nano S screen, and the speed is also too fast.

I saw that for some cryptos it shows only the beginning and the end, omitting the middle part, what makes it much simpler and user friendly. Isn't it possible to do it for all of them? And what are the risks of it?

Another idea would be to navigate through the address using the buttons and confirm it pressing both at the same time, or even some kind of 'checksum' of the address on the device and Ledger Live and simplify it to only 6 digits for example.

**Comment by teams2ua** [comment]
Hello @ibiscp , 
Thank you for the issue report.
This is probably wrong repo for this issue.
How does address is displayed on device is managed by the corresponding device-application, for example for bitcoin https://github.com/LedgerHQ/ledger-app-btc . 
Regarding the checksum approach. It is a good idea, but it needs to be worked out very well and on the level of bitcoin protocol - the user shoudn't trust Ledger Live, if hackers compromise Ledger Live it can trick the user to sign something he is not completly sure about (he didn't actually see the reciepent address on device screen, just some hash, but was it the hash of correct address he can't know).
Feel free to create an issue in device-application repo, I will close this one.
Thanks again.
