### ISSUE TITLE
Coin integration: Zel

### ISSUE THREAD

**Issue by Cabecinha84** [LedgerHQ/lib-ledger-core#277]
Is it possible to add Zel to Ledger?
https://zel.network/
https://twitter.com/zelcash
https://coinmarketcap.com/currencies/zelcash/

Thank you.

**Comment by phaazon** [comment]
Hello,

Thank you for your contribution. Feel free to read the [contribution document](https://github.com/LedgerHQ/lib-ledger-core/blob/master/CONTRIBUTING.md#about-coin-integration) about coin integration. We do not accept them so far but we might _at some day_.

**Comment by P4R4DiSi4C** [comment]
Would love to see ZEL added too.

**Comment by gagbo** [comment]
Closing because of Core status.

See [this comment](https://github.com/LedgerHQ/lib-ledger-core/issues/164#issuecomment-868415654) for more details
