### ISSUE TITLE
not installing due to an error

### ISSUE THREAD

**Issue by qubesosmacbook** [LedgerHQ/lib-ledger-core#28]
$ cmake -DCMAKE_INSTALL_PREFIX=/path/to/qt5 ../lib-ledger-core && make
-- CMake version: 3.11.2
-- Build type: 
CMake Error at core/lib/CMakeLists.txt:18 (add_subdirectory):
  The source directory

    /home/lib-ledger-core/core/lib/spdlog

  does not contain a CMakeLists.txt file.

-- Configuring SOCI: 
-- SOCI_VERSION                             = 3.2.3 
-- SOCI_ABI_VERSION                         = 3.2 
-- SOCI_PLATFORM_NAME                       = x64 
-- SOCI_COMPILER_NAME                       = gcc-8 
-- SOCI_SHARED                              = OFF 
-- SOCI_STATIC                              = ON 
-- SOCI_TESTS                               = ON 
-- Looking for SOCI dependencies: 
-- Boost: 
CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:587 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindBoost.cmake:950 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake/Modules/FindBoost.cmake:1618 (_Boost_MISSING_DEPENDENCIES)
  core/lib/soci/cmake/dependencies/Boost.cmake:5 (find_package)
  core/lib/soci/cmake/SociDependencies.cmake:77 (include)
  core/lib/soci/CMakeLists.txt:68 (include)

-- WARNING: 
-- Boost not found, some libraries or features will be disabled. 
-- See the documentation for Boost or manually set these variables: 
-- BOOST_RELEASE_VERSION                    =  
-- BOOST_INCLUDE_DIR                        =  
-- BOOST_LIBRARIES                          =  
-- MySQL: 
-- MySQL not found.
-- MySQL Embedded not found.
-- WARNING: 
-- MySQL not found, some libraries or features will be disabled. 
-- See the documentation for MySQL or manually set these variables: 
-- MYSQL_INCLUDE_DIR                        = MYSQL_INCLUDE_DIR-NOTFOUND 
-- MYSQL_LIBRARIES                          = MYSQL_LIBRARIES-NOTFOUND 
-- ODBC: 
-- WARNING: 
-- ODBC not found, some libraries or features will be disabled. 
-- See the documentation for ODBC or manually set these variables: 
-- ODBC_INCLUDE_DIR                         = ODBC_INCLUDE_DIR-NOTFOUND 
-- ODBC_LIBRARIES                           = ODBC_LIBRARY-NOTFOUND 
-- Oracle: 
-- WARNING: 
-- Oracle not found, some libraries or features will be disabled. 
-- See the documentation for Oracle or manually set these variables: 
-- ORACLE_INCLUDE_DIR                       =  
-- ORACLE_LIBRARIES                         =  
-- PostgreSQL: 
-- WARNING: 
-- PostgreSQL not found, some libraries or features will be disabled. 
-- See the documentation for PostgreSQL or manually set these variables: 
-- POSTGRESQL_INCLUDE_DIR                   = POSTGRESQL_INCLUDE_DIR-NOTFOUND 
-- POSTGRESQL_LIBRARIES                     = POSTGRESQL_LIBRARIES-NOTFOUND 
-- POSTGRESQL_VERSION                       = unknown 
-- SQLite3: 
-- WARNING: 
-- SQLite3 not found, some libraries or features will be disabled. 
-- See the documentation for SQLite3 or manually set these variables: 
-- SQLITE3_INCLUDE_DIR                      = /usr/bin 
-- SQLITE3_LIBRARIES                        = SQLITE3_LIBRARY-NOTFOUND 
-- Firebird: 
-- WARNING: 
-- Firebird not found, some libraries or features will be disabled. 
-- See the documentation for Firebird or manually set these variables: 
-- FIREBIRD_INCLUDE_DIR                     = FIREBIRD_INCLUDE_DIR-NOTFOUND 
-- FIREBIRD_LIBRARIES                       = FIREBIRD_LIBRARIES-NOTFOUND 
-- FIREBIRD_VERSION                         =  
-- DB2: 
-- WARNING: 
-- DB2 not found, some libraries or features will be disabled. 
-- See the documentation for DB2 or manually set these variables: 
-- DB2_INCLUDE_DIR                          = DB2_INCLUDE_DIR-NOTFOUND 
-- DB2_LIBRARIES                            = DB2_LIBRARY-NOTFOUND 
-- Configuring SOCI core library: 
-- SOCI_CORE_TARGET                         = soci_core 
-- SOCI_CORE_TARGET_OUTPUT_NAME             = soci_core 
-- SOCI_CORE_DEPENDENCIES                   = -lpthread /usr/lib64/libdl.so 
-- WITH_BOOST                               = ON 
-- COMPILE_DEFINITIONS                      = SOCI_ABI_VERSION="3.2" HAVE_DL=1 SOCI_LIB_PREFIX="libsoci_" SOCI_LIB_SUFFIX=".so" 
-- Configuring SOCI database backends: 
-- MySQL not found.
-- MySQL Embedded not found.
-- 
-- Configuring incomplete, errors occurred!
See also "/home/fedora/CMakeFiles/CMakeOutput.log".
See also "/home/fedora/CMakeFiles/CMakeError.log".

Hi

I get this error when i cmake. Could you help me, level beginner

**Comment by marpme** [comment]
Please install `Boost` onto your system. 

This is a short guide on how to install it on Ubuntu: 
https://stackoverflow.com/a/12578564

**Comment by KhalilBellakrid** [comment]
Hello @qubesosmacbook you should init your submodules with a `git submodule init` then a `git submodule update --init` commands.
Let us know if it's ok !
