### ISSUE TITLE
Invalid "FROM" address in Ledger Live

### ISSUE THREAD

**Issue by greenknot** [LedgerHQ/lib-ledger-core#60]
Hi there,

A user reported the following issue: [this transaction](https://www.blockchain.com/btc/tx/a258b5f1907d170786e4718962d5527c63ab3feeef7e654db016dd6c75395bb7) shows a different "FROM" address in Ledger Live (screenshot attached) compared with the public one. The highlighted address shown is `16RLCxMiT6b9bCQCfQiYViqPT26JLysuVp` while the "public" one is actually `3NWraTvebTsDNHi5Swnymx7sVVPpMD6C8s`.

Thanks!

![screenshot 2018-12-19 at 14 05 01](https://user-images.githubusercontent.com/43061872/50231303-c83acb80-03ae-11e9-8e17-3d820111fb7c.png)

**Comment by Transisto** [comment]
Should go in https://github.com/LedgerHQ/ledger-live-desktop
