### ISSUE TITLE
Coin integration: THORChain (RUNE)

### ISSUE THREAD

**Issue by HildisviniOttar** [LedgerHQ/lib-ledger-core#795]
Hi, a potential consideration:

THORChain is the largest and only decentralised cross-chain exchange. Top50 token. It is based on Cosmos/Tendermint SDK. Ledger app recently approved.

Various wallets such as Trust Wallet, [ASGARDEX-electron](https://github.com/thorchain/asgardex-electron) and [app.thorswap.finance](app.thorswap.finance) have integrated THORChain send/receive: https://github.com/trustwallet/wallet-core/issues/1368

**Resources**   
SEED
https://seed.thorchain.info/
THORNODE API 
https://thornode.thorchain.info/thorchain/doc/
MIDGARD API V2
https://midgard.thorchain.info/v2/doc
THORNODE TENDERMINT RPC
https://rpc.thorchain.info
MAINNET CHAINS CLIENTS
https://bnb.thorchain.info
https://btc.thorchain.info
https://eth.thorchain.info
https://bch.thorchain.info
https://ltc.thorchain.info
`m/44'/931'/0'/0/0`
https://viewblock.io/thorchain
https://github.com/xchainjs/xchainjs-lib
https://docs.thorchain.org

**Future**
Similar to Trust Wallet, once integrated coin, LedgerLive use can use decentralised swaps and liquidity ("LP") in the same way ShapeShift are using THORChain, including optional [affiliate fees](https://docs.thorchain.org/developers/transaction-memos#affiliate-fees). This is as simple as sending funds with a [memo](https://docs.thorchain.org/developers/transaction-memos) to the current [inbound vault](https://thornode.thorchain.info/thorchain/inbound_addresses) (or router).

**Comment by gagbo** [comment]
Hello,

(Disclaimer: this is just a fast answer from me, my views are my own and don't reflect what my employers think. Bla bla bla...)

The tracking issue for those actually is https://github.com/LedgerHQ/lib-ledger-core/issues/164

With that being said, this project is being deprecated in favor integrating wallet features directly in https://github.com/LedgerHQ/ledger-live-common in JS. Please go to [the new developer portal](https://blog.ledger.com/developer-portal/) for more information about integrating a new coin.

Regards,
Gerry
